<a href="https://colab.research.google.com/github/LAKSHMIROHI/AI_ML_Avanthi_Rohitha/blob/main/1_2_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([123])
print(a)

[123]


In [ ]:
import numpy as np
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
a.size

1

In [ ]:
a=np.array([1,2,3],dtype='int64')
a.itemsize

8

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#to get a specific element[r,c]
a[1,5]

13

In [ ]:
#to get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#to get a specific column
a[:,2]

array([ 3, 10])

In [ ]:
#row,start index:end index:increment
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [ ]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b=np.array([[[1,2],[3,4]],[5,6]]])
print(b)

[[list([1, 2]) list([3, 4])]
 [5 6]
 [7 8]]


<ipython-input-18-1af1c0494912>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[[1,2],[3,4]],[5,6],[7,8]])


In [ ]:
#to get a specific element
b[0,1,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
#replace
b[0,1,1]

In [ ]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a)

[[1 2 3 4]
 [2 3 4 5]]


In [ ]:
#print the matrix with an outer square with 1 and middle square with 0 and the middle number 9
a=np.ones((5,5))
inside=np.zeros((3,3))
inside[1,1]=9
a[1:4,-4:-1]=inside
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
 a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])